[package]
name = "ai"
version = "0.1.0"
edition = "2021"

[lib]
name = "ai"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
dirs = "4.0.0"
reqwest = { version = "0.11.14", features = ["blocking", "json"] }
rustc-serialize = "0.3.24"
rustyline = "10.1.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
